// Code generated by protoc-gen-go. DO NOT EDIT.
// source: syzoj.judge.proto

package judge

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	model "github.com/syzoj/syzoj-ng-go/model"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JudgerAuth struct {
	JudgerId             *string  `protobuf:"bytes,1,opt,name=judger_id,json=judgerId" json:"judger_id,omitempty"`
	JudgerToken          *string  `protobuf:"bytes,2,opt,name=judger_token,json=judgerToken" json:"judger_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgerAuth) Reset()         { *m = JudgerAuth{} }
func (m *JudgerAuth) String() string { return proto.CompactTextString(m) }
func (*JudgerAuth) ProtoMessage()    {}
func (*JudgerAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9594762f0e57c7, []int{0}
}

func (m *JudgerAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgerAuth.Unmarshal(m, b)
}
func (m *JudgerAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgerAuth.Marshal(b, m, deterministic)
}
func (m *JudgerAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgerAuth.Merge(m, src)
}
func (m *JudgerAuth) XXX_Size() int {
	return xxx_messageInfo_JudgerAuth.Size(m)
}
func (m *JudgerAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgerAuth.DiscardUnknown(m)
}

var xxx_messageInfo_JudgerAuth proto.InternalMessageInfo

func (m *JudgerAuth) GetJudgerId() string {
	if m != nil && m.JudgerId != nil {
		return *m.JudgerId
	}
	return ""
}

func (m *JudgerAuth) GetJudgerToken() string {
	if m != nil && m.JudgerToken != nil {
		return *m.JudgerToken
	}
	return ""
}

type FetchTaskRequest struct {
	Auth                 *JudgerAuth `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FetchTaskRequest) Reset()         { *m = FetchTaskRequest{} }
func (m *FetchTaskRequest) String() string { return proto.CompactTextString(m) }
func (*FetchTaskRequest) ProtoMessage()    {}
func (*FetchTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9594762f0e57c7, []int{1}
}

func (m *FetchTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchTaskRequest.Unmarshal(m, b)
}
func (m *FetchTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchTaskRequest.Marshal(b, m, deterministic)
}
func (m *FetchTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchTaskRequest.Merge(m, src)
}
func (m *FetchTaskRequest) XXX_Size() int {
	return xxx_messageInfo_FetchTaskRequest.Size(m)
}
func (m *FetchTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchTaskRequest proto.InternalMessageInfo

func (m *FetchTaskRequest) GetAuth() *JudgerAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type FetchTaskResponse struct {
	Task                 *JudgeRequest `protobuf:"bytes,16,opt,name=task" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FetchTaskResponse) Reset()         { *m = FetchTaskResponse{} }
func (m *FetchTaskResponse) String() string { return proto.CompactTextString(m) }
func (*FetchTaskResponse) ProtoMessage()    {}
func (*FetchTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9594762f0e57c7, []int{2}
}

func (m *FetchTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchTaskResponse.Unmarshal(m, b)
}
func (m *FetchTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchTaskResponse.Marshal(b, m, deterministic)
}
func (m *FetchTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchTaskResponse.Merge(m, src)
}
func (m *FetchTaskResponse) XXX_Size() int {
	return xxx_messageInfo_FetchTaskResponse.Size(m)
}
func (m *FetchTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchTaskResponse proto.InternalMessageInfo

func (m *FetchTaskResponse) GetTask() *JudgeRequest {
	if m != nil {
		return m.Task
	}
	return nil
}

type HandleTaskRequest struct {
	Auth                 *JudgerAuth    `protobuf:"bytes,1,opt,name=auth" json:"auth,omitempty"`
	Response             *JudgeResponse `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HandleTaskRequest) Reset()         { *m = HandleTaskRequest{} }
func (m *HandleTaskRequest) String() string { return proto.CompactTextString(m) }
func (*HandleTaskRequest) ProtoMessage()    {}
func (*HandleTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9594762f0e57c7, []int{3}
}

func (m *HandleTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleTaskRequest.Unmarshal(m, b)
}
func (m *HandleTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleTaskRequest.Marshal(b, m, deterministic)
}
func (m *HandleTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleTaskRequest.Merge(m, src)
}
func (m *HandleTaskRequest) XXX_Size() int {
	return xxx_messageInfo_HandleTaskRequest.Size(m)
}
func (m *HandleTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleTaskRequest proto.InternalMessageInfo

func (m *HandleTaskRequest) GetAuth() *JudgerAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *HandleTaskRequest) GetResponse() *JudgeResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

type HandleTaskResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandleTaskResponse) Reset()         { *m = HandleTaskResponse{} }
func (m *HandleTaskResponse) String() string { return proto.CompactTextString(m) }
func (*HandleTaskResponse) ProtoMessage()    {}
func (*HandleTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9594762f0e57c7, []int{4}
}

func (m *HandleTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleTaskResponse.Unmarshal(m, b)
}
func (m *HandleTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleTaskResponse.Marshal(b, m, deterministic)
}
func (m *HandleTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleTaskResponse.Merge(m, src)
}
func (m *HandleTaskResponse) XXX_Size() int {
	return xxx_messageInfo_HandleTaskResponse.Size(m)
}
func (m *HandleTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleTaskResponse proto.InternalMessageInfo

type JudgeRequest struct {
	// Types that are valid to be assigned to Request:
	//	*JudgeRequest_Traditional
	Request              isJudgeRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *JudgeRequest) Reset()         { *m = JudgeRequest{} }
func (m *JudgeRequest) String() string { return proto.CompactTextString(m) }
func (*JudgeRequest) ProtoMessage()    {}
func (*JudgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9594762f0e57c7, []int{5}
}

func (m *JudgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeRequest.Unmarshal(m, b)
}
func (m *JudgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeRequest.Marshal(b, m, deterministic)
}
func (m *JudgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeRequest.Merge(m, src)
}
func (m *JudgeRequest) XXX_Size() int {
	return xxx_messageInfo_JudgeRequest.Size(m)
}
func (m *JudgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeRequest proto.InternalMessageInfo

type isJudgeRequest_Request interface {
	isJudgeRequest_Request()
}

type JudgeRequest_Traditional struct {
	Traditional *TraditionalJudgeRequest `protobuf:"bytes,16,opt,name=traditional,oneof"`
}

func (*JudgeRequest_Traditional) isJudgeRequest_Request() {}

func (m *JudgeRequest) GetRequest() isJudgeRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *JudgeRequest) GetTraditional() *TraditionalJudgeRequest {
	if x, ok := m.GetRequest().(*JudgeRequest_Traditional); ok {
		return x.Traditional
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*JudgeRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*JudgeRequest_Traditional)(nil),
	}
}

type TraditionalJudgeRequest struct {
	ProblemId            *string                     `protobuf:"bytes,1,opt,name=problem_id,json=problemId" json:"problem_id,omitempty"`
	Code                 *model.TraditionalJudgeCode `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Data                 *model.TraditionalJudgeData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *TraditionalJudgeRequest) Reset()         { *m = TraditionalJudgeRequest{} }
func (m *TraditionalJudgeRequest) String() string { return proto.CompactTextString(m) }
func (*TraditionalJudgeRequest) ProtoMessage()    {}
func (*TraditionalJudgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9594762f0e57c7, []int{6}
}

func (m *TraditionalJudgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraditionalJudgeRequest.Unmarshal(m, b)
}
func (m *TraditionalJudgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraditionalJudgeRequest.Marshal(b, m, deterministic)
}
func (m *TraditionalJudgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraditionalJudgeRequest.Merge(m, src)
}
func (m *TraditionalJudgeRequest) XXX_Size() int {
	return xxx_messageInfo_TraditionalJudgeRequest.Size(m)
}
func (m *TraditionalJudgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TraditionalJudgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TraditionalJudgeRequest proto.InternalMessageInfo

func (m *TraditionalJudgeRequest) GetProblemId() string {
	if m != nil && m.ProblemId != nil {
		return *m.ProblemId
	}
	return ""
}

func (m *TraditionalJudgeRequest) GetCode() *model.TraditionalJudgeCode {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *TraditionalJudgeRequest) GetData() *model.TraditionalJudgeData {
	if m != nil {
		return m.Data
	}
	return nil
}

type JudgeResponse struct {
	// Types that are valid to be assigned to Response:
	//	*JudgeResponse_String_
	Response             isJudgeResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *JudgeResponse) Reset()         { *m = JudgeResponse{} }
func (m *JudgeResponse) String() string { return proto.CompactTextString(m) }
func (*JudgeResponse) ProtoMessage()    {}
func (*JudgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9594762f0e57c7, []int{7}
}

func (m *JudgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeResponse.Unmarshal(m, b)
}
func (m *JudgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeResponse.Marshal(b, m, deterministic)
}
func (m *JudgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeResponse.Merge(m, src)
}
func (m *JudgeResponse) XXX_Size() int {
	return xxx_messageInfo_JudgeResponse.Size(m)
}
func (m *JudgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeResponse proto.InternalMessageInfo

type isJudgeResponse_Response interface {
	isJudgeResponse_Response()
}

type JudgeResponse_String_ struct {
	String_ *JudgeStringResponse `protobuf:"bytes,16,opt,name=string,oneof"`
}

func (*JudgeResponse_String_) isJudgeResponse_Response() {}

func (m *JudgeResponse) GetResponse() isJudgeResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *JudgeResponse) GetString_() *JudgeStringResponse {
	if x, ok := m.GetResponse().(*JudgeResponse_String_); ok {
		return x.String_
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*JudgeResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*JudgeResponse_String_)(nil),
	}
}

type JudgeStringResponse struct {
	Message              *string  `protobuf:"bytes,16,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeStringResponse) Reset()         { *m = JudgeStringResponse{} }
func (m *JudgeStringResponse) String() string { return proto.CompactTextString(m) }
func (*JudgeStringResponse) ProtoMessage()    {}
func (*JudgeStringResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9594762f0e57c7, []int{8}
}

func (m *JudgeStringResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeStringResponse.Unmarshal(m, b)
}
func (m *JudgeStringResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeStringResponse.Marshal(b, m, deterministic)
}
func (m *JudgeStringResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeStringResponse.Merge(m, src)
}
func (m *JudgeStringResponse) XXX_Size() int {
	return xxx_messageInfo_JudgeStringResponse.Size(m)
}
func (m *JudgeStringResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeStringResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeStringResponse proto.InternalMessageInfo

func (m *JudgeStringResponse) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*JudgerAuth)(nil), "syzoj.judge.JudgerAuth")
	proto.RegisterType((*FetchTaskRequest)(nil), "syzoj.judge.FetchTaskRequest")
	proto.RegisterType((*FetchTaskResponse)(nil), "syzoj.judge.FetchTaskResponse")
	proto.RegisterType((*HandleTaskRequest)(nil), "syzoj.judge.HandleTaskRequest")
	proto.RegisterType((*HandleTaskResponse)(nil), "syzoj.judge.HandleTaskResponse")
	proto.RegisterType((*JudgeRequest)(nil), "syzoj.judge.JudgeRequest")
	proto.RegisterType((*TraditionalJudgeRequest)(nil), "syzoj.judge.TraditionalJudgeRequest")
	proto.RegisterType((*JudgeResponse)(nil), "syzoj.judge.JudgeResponse")
	proto.RegisterType((*JudgeStringResponse)(nil), "syzoj.judge.JudgeStringResponse")
}

func init() { proto.RegisterFile("syzoj.judge.proto", fileDescriptor_8d9594762f0e57c7) }

var fileDescriptor_8d9594762f0e57c7 = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4f, 0x6b, 0xd4, 0x40,
	0x14, 0xef, 0xea, 0x62, 0x9b, 0x97, 0x0a, 0xdd, 0x51, 0x68, 0x8c, 0x54, 0xdb, 0xc1, 0x43, 0x51,
	0x36, 0x81, 0x05, 0x3d, 0x78, 0x11, 0xa3, 0x48, 0x5a, 0xf4, 0x32, 0x5d, 0x10, 0xbc, 0xc8, 0x34,
	0x33, 0x24, 0xe9, 0x26, 0x99, 0x75, 0x66, 0x22, 0xea, 0x07, 0x12, 0xfc, 0x96, 0xb2, 0x93, 0xd9,
	0x66, 0xd2, 0xed, 0x82, 0x78, 0x09, 0xe4, 0xfd, 0xfe, 0xbd, 0x79, 0xef, 0xc1, 0x44, 0xfd, 0xfc,
	0x25, 0xae, 0xa2, 0xab, 0x96, 0xe5, 0x3c, 0x5a, 0x4a, 0xa1, 0x05, 0xf2, 0x9d, 0x52, 0x68, 0xf1,
	0x5a, 0x30, 0x5e, 0x75, 0x38, 0xfe, 0x08, 0x70, 0xbe, 0xc2, 0xe4, 0xdb, 0x56, 0x17, 0xe8, 0x31,
	0x78, 0x86, 0x29, 0xbf, 0x96, 0x2c, 0x18, 0x1d, 0x8f, 0x4e, 0x3d, 0xb2, 0xd7, 0x15, 0xce, 0x18,
	0x3a, 0x81, 0x7d, 0x0b, 0x6a, 0xb1, 0xe0, 0x4d, 0x70, 0xc7, 0xe0, 0x7e, 0x57, 0x9b, 0xaf, 0x4a,
	0xf8, 0x0d, 0x1c, 0x7c, 0xe0, 0x3a, 0x2b, 0xe6, 0x54, 0x2d, 0x08, 0xff, 0xd6, 0x72, 0xa5, 0xd1,
	0x0b, 0x18, 0xd3, 0x56, 0x17, 0xc6, 0xce, 0x9f, 0x1d, 0x46, 0x6e, 0x8f, 0x7d, 0x34, 0x31, 0x24,
	0x9c, 0xc0, 0xc4, 0x31, 0x50, 0x4b, 0xd1, 0x28, 0x8e, 0xa6, 0x30, 0xd6, 0x54, 0x2d, 0x82, 0x03,
	0xe3, 0xf0, 0x68, 0xd3, 0xc1, 0x46, 0x11, 0x43, 0xc3, 0x3f, 0x60, 0x92, 0xd2, 0x86, 0x55, 0xfc,
	0x7f, 0xbb, 0x40, 0xaf, 0x60, 0x4f, 0xda, 0x70, 0xf3, 0x4a, 0x7f, 0x16, 0xde, 0x16, 0xda, 0x31,
	0xc8, 0x35, 0x17, 0x3f, 0x04, 0xe4, 0x26, 0xdb, 0x6a, 0x06, 0xfb, 0x6e, 0x97, 0x28, 0x05, 0x5f,
	0x4b, 0xca, 0x4a, 0x5d, 0x8a, 0x86, 0x56, 0xf6, 0x55, 0xcf, 0x06, 0x01, 0xf3, 0x1e, 0x77, 0xa5,
	0xe9, 0x0e, 0x71, 0xa5, 0x89, 0x07, 0xbb, 0xb2, 0x43, 0xf0, 0xef, 0x11, 0x1c, 0x6e, 0x51, 0xa1,
	0x23, 0x80, 0xa5, 0x14, 0x97, 0x15, 0xaf, 0xfb, 0xb5, 0x7a, 0xb6, 0x72, 0xc6, 0xd0, 0x4b, 0x18,
	0x67, 0x82, 0xad, 0x5f, 0x7a, 0x12, 0xb9, 0x47, 0x72, 0xd3, 0xf2, 0x9d, 0x60, 0x9c, 0x18, 0xfa,
	0x4a, 0xc6, 0xa8, 0xa6, 0xc1, 0xdd, 0x7f, 0x90, 0xbd, 0xa7, 0x9a, 0x12, 0x43, 0xc7, 0x9f, 0xe1,
	0xfe, 0x60, 0x7c, 0xe8, 0x35, 0xdc, 0x53, 0x5a, 0x96, 0x4d, 0x6e, 0x27, 0x71, 0xbc, 0x39, 0xea,
	0x0b, 0x83, 0xaf, 0x15, 0xe9, 0x0e, 0xb1, 0x8a, 0x04, 0xfa, 0x45, 0xe1, 0x18, 0x1e, 0xdc, 0x42,
	0x46, 0x01, 0xec, 0xd6, 0x5c, 0x29, 0x9a, 0x73, 0xe3, 0xef, 0x91, 0xf5, 0xef, 0xec, 0xcf, 0xc8,
	0x2e, 0xe6, 0x82, 0xcb, 0xef, 0x65, 0xc6, 0xd1, 0x39, 0x78, 0xd7, 0xc7, 0x87, 0x8e, 0x06, 0x6d,
	0xdc, 0xbc, 0xea, 0xf0, 0xc9, 0x36, 0xd8, 0xc6, 0x7e, 0x02, 0xe8, 0x4f, 0x01, 0x0d, 0xd9, 0x1b,
	0xd7, 0x19, 0x3e, 0xdd, 0x8a, 0x77, 0x76, 0xc9, 0xf3, 0x2f, 0xa7, 0x79, 0xa9, 0x8b, 0xf6, 0x32,
	0xca, 0x44, 0x1d, 0x1b, 0x72, 0xf7, 0x9d, 0x36, 0xf9, 0x34, 0x17, 0xb1, 0x19, 0x7b, 0x6c, 0xe4,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xf5, 0x03, 0x91, 0x06, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JudgeServiceClient is the client API for JudgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JudgeServiceClient interface {
	FetchTask(ctx context.Context, in *FetchTaskRequest, opts ...grpc.CallOption) (*FetchTaskResponse, error)
	HandleTask(ctx context.Context, in *HandleTaskRequest, opts ...grpc.CallOption) (*HandleTaskResponse, error)
}

type judgeServiceClient struct {
	cc *grpc.ClientConn
}

func NewJudgeServiceClient(cc *grpc.ClientConn) JudgeServiceClient {
	return &judgeServiceClient{cc}
}

func (c *judgeServiceClient) FetchTask(ctx context.Context, in *FetchTaskRequest, opts ...grpc.CallOption) (*FetchTaskResponse, error) {
	out := new(FetchTaskResponse)
	err := c.cc.Invoke(ctx, "/syzoj.judge.JudgeService/FetchTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeServiceClient) HandleTask(ctx context.Context, in *HandleTaskRequest, opts ...grpc.CallOption) (*HandleTaskResponse, error) {
	out := new(HandleTaskResponse)
	err := c.cc.Invoke(ctx, "/syzoj.judge.JudgeService/HandleTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JudgeServiceServer is the server API for JudgeService service.
type JudgeServiceServer interface {
	FetchTask(context.Context, *FetchTaskRequest) (*FetchTaskResponse, error)
	HandleTask(context.Context, *HandleTaskRequest) (*HandleTaskResponse, error)
}

func RegisterJudgeServiceServer(s *grpc.Server, srv JudgeServiceServer) {
	s.RegisterService(&_JudgeService_serviceDesc, srv)
}

func _JudgeService_FetchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).FetchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syzoj.judge.JudgeService/FetchTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).FetchTask(ctx, req.(*FetchTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JudgeService_HandleTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServiceServer).HandleTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syzoj.judge.JudgeService/HandleTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServiceServer).HandleTask(ctx, req.(*HandleTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JudgeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "syzoj.judge.JudgeService",
	HandlerType: (*JudgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchTask",
			Handler:    _JudgeService_FetchTask_Handler,
		},
		{
			MethodName: "HandleTask",
			Handler:    _JudgeService_HandleTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "syzoj.judge.proto",
}
