// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: syzoj.model.proto

package model // import "github.com/syzoj/syzoj-ng-go/model"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import encoding_binary "encoding/binary"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// UserAuth defines all the information necessary to authenticate a user.
type UserAuth struct {
	PasswordHash         []byte   `protobuf:"bytes,1,opt,name=password_hash,json=passwordHash" json:"password_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAuth) Reset()         { *m = UserAuth{} }
func (m *UserAuth) String() string { return proto.CompactTextString(m) }
func (*UserAuth) ProtoMessage()    {}
func (*UserAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_model_547f602117ab1494, []int{0}
}
func (m *UserAuth) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserAuth.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *UserAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuth.Merge(dst, src)
}
func (m *UserAuth) XXX_Size() int {
	return m.Size()
}
func (m *UserAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuth.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuth proto.InternalMessageInfo

func (m *UserAuth) GetPasswordHash() []byte {
	if m != nil {
		return m.PasswordHash
	}
	return nil
}

// DeviceInfo defines the immutable part of a device's identity.
type DeviceInfo struct {
	Token                *string  `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	UserAgent            *string  `protobuf:"bytes,16,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	RemoteAddr           *string  `protobuf:"bytes,17,opt,name=remote_addr,json=remoteAddr" json:"remote_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceInfo) Reset()         { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()    {}
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_model_547f602117ab1494, []int{1}
}
func (m *DeviceInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeviceInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *DeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfo.Merge(dst, src)
}
func (m *DeviceInfo) XXX_Size() int {
	return m.Size()
}
func (m *DeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfo proto.InternalMessageInfo

func (m *DeviceInfo) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *DeviceInfo) GetUserAgent() string {
	if m != nil && m.UserAgent != nil {
		return *m.UserAgent
	}
	return ""
}

func (m *DeviceInfo) GetRemoteAddr() string {
	if m != nil && m.RemoteAddr != nil {
		return *m.RemoteAddr
	}
	return ""
}

// Problem defines a problem.
type Problem struct {
	Title                *string           `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Statement            *ProblemStatement `protobuf:"bytes,2,opt,name=statement" json:"statement,omitempty"`
	Source               []*ProblemSource  `protobuf:"bytes,3,rep,name=source" json:"source,omitempty"`
	Judge                *ProblemJudge     `protobuf:"bytes,4,opt,name=judge" json:"judge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Problem) Reset()         { *m = Problem{} }
func (m *Problem) String() string { return proto.CompactTextString(m) }
func (*Problem) ProtoMessage()    {}
func (*Problem) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_model_547f602117ab1494, []int{2}
}
func (m *Problem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Problem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Problem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Problem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Problem.Merge(dst, src)
}
func (m *Problem) XXX_Size() int {
	return m.Size()
}
func (m *Problem) XXX_DiscardUnknown() {
	xxx_messageInfo_Problem.DiscardUnknown(m)
}

var xxx_messageInfo_Problem proto.InternalMessageInfo

func (m *Problem) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Problem) GetStatement() *ProblemStatement {
	if m != nil {
		return m.Statement
	}
	return nil
}

func (m *Problem) GetSource() []*ProblemSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Problem) GetJudge() *ProblemJudge {
	if m != nil {
		return m.Judge
	}
	return nil
}

type ProblemJudge struct {
	// Types that are valid to be assigned to Judge:
	//	*ProblemJudge_Traditional
	Judge                isProblemJudge_Judge `protobuf_oneof:"judge"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProblemJudge) Reset()         { *m = ProblemJudge{} }
func (m *ProblemJudge) String() string { return proto.CompactTextString(m) }
func (*ProblemJudge) ProtoMessage()    {}
func (*ProblemJudge) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_model_547f602117ab1494, []int{3}
}
func (m *ProblemJudge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProblemJudge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProblemJudge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ProblemJudge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemJudge.Merge(dst, src)
}
func (m *ProblemJudge) XXX_Size() int {
	return m.Size()
}
func (m *ProblemJudge) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemJudge.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemJudge proto.InternalMessageInfo

type isProblemJudge_Judge interface {
	isProblemJudge_Judge()
	MarshalTo([]byte) (int, error)
	Size() int
}

type ProblemJudge_Traditional struct {
	Traditional *TraditionalJudgeData `protobuf:"bytes,1,opt,name=traditional,oneof"`
}

func (*ProblemJudge_Traditional) isProblemJudge_Judge() {}

func (m *ProblemJudge) GetJudge() isProblemJudge_Judge {
	if m != nil {
		return m.Judge
	}
	return nil
}

func (m *ProblemJudge) GetTraditional() *TraditionalJudgeData {
	if x, ok := m.GetJudge().(*ProblemJudge_Traditional); ok {
		return x.Traditional
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ProblemJudge) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ProblemJudge_OneofMarshaler, _ProblemJudge_OneofUnmarshaler, _ProblemJudge_OneofSizer, []interface{}{
		(*ProblemJudge_Traditional)(nil),
	}
}

func _ProblemJudge_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ProblemJudge)
	// judge
	switch x := m.Judge.(type) {
	case *ProblemJudge_Traditional:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Traditional); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ProblemJudge.Judge has unexpected type %T", x)
	}
	return nil
}

func _ProblemJudge_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ProblemJudge)
	switch tag {
	case 1: // judge.traditional
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TraditionalJudgeData)
		err := b.DecodeMessage(msg)
		m.Judge = &ProblemJudge_Traditional{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ProblemJudge_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ProblemJudge)
	// judge
	switch x := m.Judge.(type) {
	case *ProblemJudge_Traditional:
		s := proto.Size(x.Traditional)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// ProblemSource defines the content of a problem's source.
type ProblemSource struct {
	Url                  *string  `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	SiteName             *string  `protobuf:"bytes,2,opt,name=site_name,json=siteName" json:"site_name,omitempty"`
	SiteProblemTitle     *string  `protobuf:"bytes,3,opt,name=site_problem_title,json=siteProblemTitle" json:"site_problem_title,omitempty"`
	ContestName          *string  `protobuf:"bytes,4,opt,name=contest_name,json=contestName" json:"contest_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProblemSource) Reset()         { *m = ProblemSource{} }
func (m *ProblemSource) String() string { return proto.CompactTextString(m) }
func (*ProblemSource) ProtoMessage()    {}
func (*ProblemSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_model_547f602117ab1494, []int{4}
}
func (m *ProblemSource) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProblemSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProblemSource.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ProblemSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemSource.Merge(dst, src)
}
func (m *ProblemSource) XXX_Size() int {
	return m.Size()
}
func (m *ProblemSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemSource.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemSource proto.InternalMessageInfo

func (m *ProblemSource) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *ProblemSource) GetSiteName() string {
	if m != nil && m.SiteName != nil {
		return *m.SiteName
	}
	return ""
}

func (m *ProblemSource) GetSiteProblemTitle() string {
	if m != nil && m.SiteProblemTitle != nil {
		return *m.SiteProblemTitle
	}
	return ""
}

func (m *ProblemSource) GetContestName() string {
	if m != nil && m.ContestName != nil {
		return *m.ContestName
	}
	return ""
}

type ProblemStatement struct {
	// Types that are valid to be assigned to Statement:
	//	*ProblemStatement_Markdown
	Statement            isProblemStatement_Statement `protobuf_oneof:"statement"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ProblemStatement) Reset()         { *m = ProblemStatement{} }
func (m *ProblemStatement) String() string { return proto.CompactTextString(m) }
func (*ProblemStatement) ProtoMessage()    {}
func (*ProblemStatement) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_model_547f602117ab1494, []int{5}
}
func (m *ProblemStatement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProblemStatement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProblemStatement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ProblemStatement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemStatement.Merge(dst, src)
}
func (m *ProblemStatement) XXX_Size() int {
	return m.Size()
}
func (m *ProblemStatement) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemStatement.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemStatement proto.InternalMessageInfo

type isProblemStatement_Statement interface {
	isProblemStatement_Statement()
	MarshalTo([]byte) (int, error)
	Size() int
}

type ProblemStatement_Markdown struct {
	Markdown *MarkdownLatexDocument `protobuf:"bytes,16,opt,name=markdown,oneof"`
}

func (*ProblemStatement_Markdown) isProblemStatement_Statement() {}

func (m *ProblemStatement) GetStatement() isProblemStatement_Statement {
	if m != nil {
		return m.Statement
	}
	return nil
}

func (m *ProblemStatement) GetMarkdown() *MarkdownLatexDocument {
	if x, ok := m.GetStatement().(*ProblemStatement_Markdown); ok {
		return x.Markdown
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ProblemStatement) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ProblemStatement_OneofMarshaler, _ProblemStatement_OneofUnmarshaler, _ProblemStatement_OneofSizer, []interface{}{
		(*ProblemStatement_Markdown)(nil),
	}
}

func _ProblemStatement_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ProblemStatement)
	// statement
	switch x := m.Statement.(type) {
	case *ProblemStatement_Markdown:
		_ = b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Markdown); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ProblemStatement.Statement has unexpected type %T", x)
	}
	return nil
}

func _ProblemStatement_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ProblemStatement)
	switch tag {
	case 16: // statement.markdown
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MarkdownLatexDocument)
		err := b.DecodeMessage(msg)
		m.Statement = &ProblemStatement_Markdown{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ProblemStatement_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ProblemStatement)
	// statement
	switch x := m.Statement.(type) {
	case *ProblemStatement_Markdown:
		s := proto.Size(x.Markdown)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type MarkdownLatexDocument struct {
	Text                 *string  `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkdownLatexDocument) Reset()         { *m = MarkdownLatexDocument{} }
func (m *MarkdownLatexDocument) String() string { return proto.CompactTextString(m) }
func (*MarkdownLatexDocument) ProtoMessage()    {}
func (*MarkdownLatexDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_model_547f602117ab1494, []int{6}
}
func (m *MarkdownLatexDocument) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MarkdownLatexDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MarkdownLatexDocument.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *MarkdownLatexDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkdownLatexDocument.Merge(dst, src)
}
func (m *MarkdownLatexDocument) XXX_Size() int {
	return m.Size()
}
func (m *MarkdownLatexDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkdownLatexDocument.DiscardUnknown(m)
}

var xxx_messageInfo_MarkdownLatexDocument proto.InternalMessageInfo

func (m *MarkdownLatexDocument) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type TraditionalJudgeData struct {
	TimeLimit            *float64 `protobuf:"fixed64,16,opt,name=time_limit,json=timeLimit" json:"time_limit,omitempty"`
	MemoryLimit          *float64 `protobuf:"fixed64,17,opt,name=memory_limit,json=memoryLimit" json:"memory_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraditionalJudgeData) Reset()         { *m = TraditionalJudgeData{} }
func (m *TraditionalJudgeData) String() string { return proto.CompactTextString(m) }
func (*TraditionalJudgeData) ProtoMessage()    {}
func (*TraditionalJudgeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_model_547f602117ab1494, []int{7}
}
func (m *TraditionalJudgeData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TraditionalJudgeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TraditionalJudgeData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *TraditionalJudgeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraditionalJudgeData.Merge(dst, src)
}
func (m *TraditionalJudgeData) XXX_Size() int {
	return m.Size()
}
func (m *TraditionalJudgeData) XXX_DiscardUnknown() {
	xxx_messageInfo_TraditionalJudgeData.DiscardUnknown(m)
}

var xxx_messageInfo_TraditionalJudgeData proto.InternalMessageInfo

func (m *TraditionalJudgeData) GetTimeLimit() float64 {
	if m != nil && m.TimeLimit != nil {
		return *m.TimeLimit
	}
	return 0
}

func (m *TraditionalJudgeData) GetMemoryLimit() float64 {
	if m != nil && m.MemoryLimit != nil {
		return *m.MemoryLimit
	}
	return 0
}

type TraditionalJudgeCode struct {
	Language             *string  `protobuf:"bytes,1,opt,name=language" json:"language,omitempty"`
	Code                 *string  `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraditionalJudgeCode) Reset()         { *m = TraditionalJudgeCode{} }
func (m *TraditionalJudgeCode) String() string { return proto.CompactTextString(m) }
func (*TraditionalJudgeCode) ProtoMessage()    {}
func (*TraditionalJudgeCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_model_547f602117ab1494, []int{8}
}
func (m *TraditionalJudgeCode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TraditionalJudgeCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TraditionalJudgeCode.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *TraditionalJudgeCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraditionalJudgeCode.Merge(dst, src)
}
func (m *TraditionalJudgeCode) XXX_Size() int {
	return m.Size()
}
func (m *TraditionalJudgeCode) XXX_DiscardUnknown() {
	xxx_messageInfo_TraditionalJudgeCode.DiscardUnknown(m)
}

var xxx_messageInfo_TraditionalJudgeCode proto.InternalMessageInfo

func (m *TraditionalJudgeCode) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *TraditionalJudgeCode) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func init() {
	proto.RegisterType((*UserAuth)(nil), "syzoj.model.UserAuth")
	proto.RegisterType((*DeviceInfo)(nil), "syzoj.model.DeviceInfo")
	proto.RegisterType((*Problem)(nil), "syzoj.model.Problem")
	proto.RegisterType((*ProblemJudge)(nil), "syzoj.model.ProblemJudge")
	proto.RegisterType((*ProblemSource)(nil), "syzoj.model.ProblemSource")
	proto.RegisterType((*ProblemStatement)(nil), "syzoj.model.ProblemStatement")
	proto.RegisterType((*MarkdownLatexDocument)(nil), "syzoj.model.MarkdownLatexDocument")
	proto.RegisterType((*TraditionalJudgeData)(nil), "syzoj.model.TraditionalJudgeData")
	proto.RegisterType((*TraditionalJudgeCode)(nil), "syzoj.model.TraditionalJudgeCode")
}
func (m *UserAuth) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserAuth) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.PasswordHash != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(len(m.PasswordHash)))
		i += copy(dAtA[i:], m.PasswordHash)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *DeviceInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeviceInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Token != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(len(*m.Token)))
		i += copy(dAtA[i:], *m.Token)
	}
	if m.UserAgent != nil {
		dAtA[i] = 0x82
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(len(*m.UserAgent)))
		i += copy(dAtA[i:], *m.UserAgent)
	}
	if m.RemoteAddr != nil {
		dAtA[i] = 0x8a
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(len(*m.RemoteAddr)))
		i += copy(dAtA[i:], *m.RemoteAddr)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Problem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Problem) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Title != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(len(*m.Title)))
		i += copy(dAtA[i:], *m.Title)
	}
	if m.Statement != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(m.Statement.Size()))
		n1, err := m.Statement.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Source) > 0 {
		for _, msg := range m.Source {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintSyzojModel(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.Judge != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(m.Judge.Size()))
		n2, err := m.Judge.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ProblemJudge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProblemJudge) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Judge != nil {
		nn3, err := m.Judge.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn3
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ProblemJudge_Traditional) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.Traditional != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(m.Traditional.Size()))
		n4, err := m.Traditional.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	return i, nil
}
func (m *ProblemSource) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProblemSource) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Url != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(len(*m.Url)))
		i += copy(dAtA[i:], *m.Url)
	}
	if m.SiteName != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(len(*m.SiteName)))
		i += copy(dAtA[i:], *m.SiteName)
	}
	if m.SiteProblemTitle != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(len(*m.SiteProblemTitle)))
		i += copy(dAtA[i:], *m.SiteProblemTitle)
	}
	if m.ContestName != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(len(*m.ContestName)))
		i += copy(dAtA[i:], *m.ContestName)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ProblemStatement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProblemStatement) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Statement != nil {
		nn5, err := m.Statement.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn5
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ProblemStatement_Markdown) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.Markdown != nil {
		dAtA[i] = 0x82
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(m.Markdown.Size()))
		n6, err := m.Markdown.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	return i, nil
}
func (m *MarkdownLatexDocument) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MarkdownLatexDocument) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Text != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(len(*m.Text)))
		i += copy(dAtA[i:], *m.Text)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *TraditionalJudgeData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TraditionalJudgeData) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TimeLimit != nil {
		dAtA[i] = 0x81
		i++
		dAtA[i] = 0x1
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(*m.TimeLimit))))
		i += 8
	}
	if m.MemoryLimit != nil {
		dAtA[i] = 0x89
		i++
		dAtA[i] = 0x1
		i++
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(*m.MemoryLimit))))
		i += 8
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *TraditionalJudgeCode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TraditionalJudgeCode) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Language != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(len(*m.Language)))
		i += copy(dAtA[i:], *m.Language)
	}
	if m.Code != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSyzojModel(dAtA, i, uint64(len(*m.Code)))
		i += copy(dAtA[i:], *m.Code)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintSyzojModel(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *UserAuth) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PasswordHash != nil {
		l = len(m.PasswordHash)
		n += 1 + l + sovSyzojModel(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DeviceInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Token != nil {
		l = len(*m.Token)
		n += 1 + l + sovSyzojModel(uint64(l))
	}
	if m.UserAgent != nil {
		l = len(*m.UserAgent)
		n += 2 + l + sovSyzojModel(uint64(l))
	}
	if m.RemoteAddr != nil {
		l = len(*m.RemoteAddr)
		n += 2 + l + sovSyzojModel(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Problem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Title != nil {
		l = len(*m.Title)
		n += 1 + l + sovSyzojModel(uint64(l))
	}
	if m.Statement != nil {
		l = m.Statement.Size()
		n += 1 + l + sovSyzojModel(uint64(l))
	}
	if len(m.Source) > 0 {
		for _, e := range m.Source {
			l = e.Size()
			n += 1 + l + sovSyzojModel(uint64(l))
		}
	}
	if m.Judge != nil {
		l = m.Judge.Size()
		n += 1 + l + sovSyzojModel(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ProblemJudge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Judge != nil {
		n += m.Judge.Size()
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ProblemJudge_Traditional) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Traditional != nil {
		l = m.Traditional.Size()
		n += 1 + l + sovSyzojModel(uint64(l))
	}
	return n
}
func (m *ProblemSource) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Url != nil {
		l = len(*m.Url)
		n += 1 + l + sovSyzojModel(uint64(l))
	}
	if m.SiteName != nil {
		l = len(*m.SiteName)
		n += 1 + l + sovSyzojModel(uint64(l))
	}
	if m.SiteProblemTitle != nil {
		l = len(*m.SiteProblemTitle)
		n += 1 + l + sovSyzojModel(uint64(l))
	}
	if m.ContestName != nil {
		l = len(*m.ContestName)
		n += 1 + l + sovSyzojModel(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ProblemStatement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Statement != nil {
		n += m.Statement.Size()
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ProblemStatement_Markdown) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Markdown != nil {
		l = m.Markdown.Size()
		n += 2 + l + sovSyzojModel(uint64(l))
	}
	return n
}
func (m *MarkdownLatexDocument) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Text != nil {
		l = len(*m.Text)
		n += 1 + l + sovSyzojModel(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TraditionalJudgeData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TimeLimit != nil {
		n += 10
	}
	if m.MemoryLimit != nil {
		n += 10
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TraditionalJudgeCode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Language != nil {
		l = len(*m.Language)
		n += 1 + l + sovSyzojModel(uint64(l))
	}
	if m.Code != nil {
		l = len(*m.Code)
		n += 1 + l + sovSyzojModel(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSyzojModel(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozSyzojModel(x uint64) (n int) {
	return sovSyzojModel(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UserAuth) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserAuth: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserAuth: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PasswordHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PasswordHash = append(m.PasswordHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PasswordHash == nil {
				m.PasswordHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeviceInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Token = &s
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAgent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.UserAgent = &s
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoteAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.RemoteAddr = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Problem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Problem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Problem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Title = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Statement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Statement == nil {
				m.Statement = &ProblemStatement{}
			}
			if err := m.Statement.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = append(m.Source, &ProblemSource{})
			if err := m.Source[len(m.Source)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Judge", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Judge == nil {
				m.Judge = &ProblemJudge{}
			}
			if err := m.Judge.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProblemJudge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProblemJudge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProblemJudge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Traditional", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &TraditionalJudgeData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Judge = &ProblemJudge_Traditional{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProblemSource) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProblemSource: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProblemSource: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Url = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SiteName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.SiteName = &s
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SiteProblemTitle", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.SiteProblemTitle = &s
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContestName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ContestName = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProblemStatement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProblemStatement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProblemStatement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Markdown", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &MarkdownLatexDocument{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Statement = &ProblemStatement_Markdown{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MarkdownLatexDocument) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MarkdownLatexDocument: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MarkdownLatexDocument: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Text", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Text = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TraditionalJudgeData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TraditionalJudgeData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TraditionalJudgeData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 16:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeLimit", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			v2 := float64(math.Float64frombits(v))
			m.TimeLimit = &v2
		case 17:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemoryLimit", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			v2 := float64(math.Float64frombits(v))
			m.MemoryLimit = &v2
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TraditionalJudgeCode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TraditionalJudgeCode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TraditionalJudgeCode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Language", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Language = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyzojModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Code = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSyzojModel(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSyzojModel
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSyzojModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthSyzojModel
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSyzojModel
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSyzojModel(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSyzojModel = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSyzojModel   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("syzoj.model.proto", fileDescriptor_syzoj_model_547f602117ab1494) }

var fileDescriptor_syzoj_model_547f602117ab1494 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x5d, 0xe8, 0xc6, 0x9a, 0x9b, 0x4e, 0xea, 0xac, 0x21, 0x95, 0xa1, 0x8d, 0xce, 0xbc, 0x54,
	0x82, 0xb5, 0xa8, 0xaf, 0xbc, 0xd0, 0x52, 0x50, 0x41, 0x03, 0xa1, 0x30, 0x24, 0xc4, 0x03, 0x91,
	0x1b, 0x5f, 0xd2, 0x6c, 0x71, 0x5c, 0xd9, 0x0e, 0xdb, 0xf8, 0x09, 0xbe, 0x89, 0x37, 0x1e, 0xf9,
	0x04, 0xd4, 0x2f, 0x41, 0x76, 0xd2, 0xae, 0x85, 0xbe, 0x44, 0xf6, 0xb9, 0xe7, 0x9c, 0xeb, 0x7b,
	0x72, 0x61, 0x5f, 0xdf, 0x7c, 0x97, 0x17, 0x5d, 0x21, 0x39, 0x66, 0xdd, 0x99, 0x92, 0x46, 0x92,
	0x60, 0x05, 0xa2, 0x3d, 0xa8, 0x7f, 0xd4, 0xa8, 0x06, 0x85, 0x99, 0x92, 0x47, 0xb0, 0x37, 0x63,
	0x5a, 0x5f, 0x49, 0xc5, 0xa3, 0x29, 0xd3, 0xd3, 0x96, 0xd7, 0xf6, 0x3a, 0x8d, 0xb0, 0xb1, 0x00,
	0xc7, 0x4c, 0x4f, 0xe9, 0x04, 0x60, 0x84, 0xdf, 0xd2, 0x18, 0x5f, 0xe7, 0x5f, 0x25, 0x39, 0x80,
	0x1d, 0x23, 0x2f, 0x31, 0x77, 0x54, 0x3f, 0x2c, 0x2f, 0xe4, 0x08, 0xa0, 0xd0, 0xa8, 0x22, 0x96,
	0x60, 0x6e, 0x5a, 0x4d, 0x57, 0xf2, 0x2d, 0x32, 0xb0, 0x00, 0x79, 0x08, 0x81, 0x42, 0x21, 0x0d,
	0x46, 0x8c, 0x73, 0xd5, 0xda, 0x77, 0x75, 0x28, 0xa1, 0x01, 0xe7, 0x8a, 0xfe, 0xf4, 0x60, 0xf7,
	0xbd, 0x92, 0x93, 0x0c, 0x85, 0xeb, 0x90, 0x9a, 0x0c, 0x97, 0x1d, 0xec, 0x85, 0x3c, 0x03, 0x5f,
	0x1b, 0x66, 0x50, 0xd8, 0x06, 0x77, 0xda, 0x5e, 0x27, 0xe8, 0x1f, 0x75, 0x57, 0x47, 0xad, 0xe4,
	0x1f, 0x16, 0xa4, 0xf0, 0x96, 0x4f, 0xfa, 0x70, 0x57, 0xcb, 0x42, 0xc5, 0xd8, 0xaa, 0xb5, 0x6b,
	0x9d, 0xa0, 0x7f, 0xb8, 0x51, 0xe9, 0x18, 0x61, 0xc5, 0x24, 0x3d, 0xd8, 0xb9, 0x28, 0x78, 0x82,
	0xad, 0x6d, 0xd7, 0xec, 0xfe, 0x26, 0xc9, 0x1b, 0x4b, 0x08, 0x4b, 0x1e, 0xfd, 0x02, 0x8d, 0x55,
	0x98, 0xbc, 0x84, 0xc0, 0x28, 0xc6, 0x53, 0x93, 0xca, 0x9c, 0x65, 0x6e, 0x9a, 0xa0, 0x7f, 0xb2,
	0x66, 0x73, 0x7e, 0x5b, 0x77, 0x9a, 0x11, 0x33, 0x6c, 0xbc, 0x15, 0xae, 0xea, 0x86, 0xbb, 0xd5,
	0x3b, 0xe8, 0x0f, 0x0f, 0xf6, 0xd6, 0x9e, 0x4a, 0x9a, 0x50, 0x2b, 0x54, 0x56, 0xe5, 0x64, 0x8f,
	0xe4, 0x01, 0xf8, 0x3a, 0x35, 0x18, 0xe5, 0x4c, 0xa0, 0x4b, 0xc9, 0x0f, 0xeb, 0x16, 0x78, 0xc7,
	0x04, 0x92, 0x27, 0x40, 0x5c, 0x71, 0x56, 0x9a, 0x44, 0x65, 0xca, 0x35, 0xc7, 0x6a, 0xda, 0x4a,
	0xe5, 0x7e, 0xee, 0x02, 0x3f, 0x81, 0x46, 0x2c, 0x73, 0x83, 0xda, 0x94, 0x6e, 0xdb, 0x8e, 0x17,
	0x54, 0x98, 0x35, 0xa4, 0x0c, 0x9a, 0xff, 0xa6, 0x4e, 0x9e, 0x43, 0x5d, 0x30, 0x75, 0xc9, 0xe5,
	0x55, 0xee, 0xf6, 0x20, 0xe8, 0xd3, 0xb5, 0x91, 0xdf, 0x56, 0xc5, 0x33, 0x66, 0xf0, 0x7a, 0x24,
	0xe3, 0xc2, 0xaa, 0xc6, 0x5b, 0xe1, 0x52, 0x35, 0x0c, 0x56, 0xfe, 0x34, 0x7d, 0x0c, 0xf7, 0x36,
	0x2a, 0x08, 0x81, 0x6d, 0x83, 0xd7, 0xa6, 0x1a, 0xde, 0x9d, 0xe9, 0x27, 0x38, 0xd8, 0x94, 0xa8,
	0xdd, 0x4e, 0x93, 0x0a, 0x8c, 0xb2, 0x54, 0xa4, 0xe5, 0x76, 0x7a, 0xa1, 0x6f, 0x91, 0x33, 0x0b,
	0xd8, 0x49, 0x05, 0x0a, 0xa9, 0x6e, 0x2a, 0xc2, 0xbe, 0x23, 0x04, 0x25, 0xe6, 0x28, 0xf4, 0xd5,
	0xff, 0xce, 0x2f, 0x24, 0x47, 0x72, 0x08, 0xf5, 0x8c, 0xe5, 0x49, 0xc1, 0x92, 0xc5, 0xba, 0x2e,
	0xef, 0xf6, 0x85, 0xb1, 0xe4, 0x8b, 0xdf, 0xe0, 0xce, 0xc3, 0xa7, 0xbf, 0xe6, 0xc7, 0xde, 0xef,
	0xf9, 0xb1, 0xf7, 0x67, 0x7e, 0xec, 0x7d, 0xa6, 0x49, 0x6a, 0xa6, 0xc5, 0xa4, 0x1b, 0x4b, 0xd1,
	0x73, 0x19, 0x95, 0xdf, 0xd3, 0x3c, 0x39, 0x4d, 0x64, 0xcf, 0xe5, 0xf5, 0x37, 0x00, 0x00, 0xff,
	0xff, 0xd9, 0x79, 0xdd, 0x32, 0xcf, 0x03, 0x00, 0x00,
}
