// Code generated by protoc-gen-go. DO NOT EDIT.
// source: syzoj.model.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Any struct {
	Data                 *any.Any `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Any) Reset()         { *m = Any{} }
func (m *Any) String() string { return proto.CompactTextString(m) }
func (*Any) ProtoMessage()    {}
func (*Any) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0f42fe9a6db7df, []int{0}
}

func (m *Any) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Any.Unmarshal(m, b)
}
func (m *Any) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Any.Marshal(b, m, deterministic)
}
func (m *Any) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Any.Merge(m, src)
}
func (m *Any) XXX_Size() int {
	return xxx_messageInfo_Any.Size(m)
}
func (m *Any) XXX_DiscardUnknown() {
	xxx_messageInfo_Any.DiscardUnknown(m)
}

var xxx_messageInfo_Any proto.InternalMessageInfo

func (m *Any) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

// UserAuth defines all the information necessary to authenticate a user.
type UserAuth struct {
	PasswordHash         []byte   `protobuf:"bytes,1,opt,name=password_hash,json=passwordHash" json:"password_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAuth) Reset()         { *m = UserAuth{} }
func (m *UserAuth) String() string { return proto.CompactTextString(m) }
func (*UserAuth) ProtoMessage()    {}
func (*UserAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0f42fe9a6db7df, []int{1}
}

func (m *UserAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAuth.Unmarshal(m, b)
}
func (m *UserAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAuth.Marshal(b, m, deterministic)
}
func (m *UserAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuth.Merge(m, src)
}
func (m *UserAuth) XXX_Size() int {
	return xxx_messageInfo_UserAuth.Size(m)
}
func (m *UserAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuth.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuth proto.InternalMessageInfo

func (m *UserAuth) GetPasswordHash() []byte {
	if m != nil {
		return m.PasswordHash
	}
	return nil
}

// DeviceInfo defines the immutable part of a device's identity.
type DeviceInfo struct {
	Token                *string  `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	UserAgent            *string  `protobuf:"bytes,16,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	Ip                   *string  `protobuf:"bytes,17,opt,name=ip" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceInfo) Reset()         { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()    {}
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0f42fe9a6db7df, []int{2}
}

func (m *DeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceInfo.Unmarshal(m, b)
}
func (m *DeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceInfo.Marshal(b, m, deterministic)
}
func (m *DeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfo.Merge(m, src)
}
func (m *DeviceInfo) XXX_Size() int {
	return xxx_messageInfo_DeviceInfo.Size(m)
}
func (m *DeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfo proto.InternalMessageInfo

func (m *DeviceInfo) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *DeviceInfo) GetUserAgent() string {
	if m != nil && m.UserAgent != nil {
		return *m.UserAgent
	}
	return ""
}

func (m *DeviceInfo) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

// ProblemSource defines the content of a problem's source.
type ProblemSource struct {
	Url                  *string  `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	SiteName             *string  `protobuf:"bytes,2,opt,name=site_name,json=siteName" json:"site_name,omitempty"`
	SiteProblemTitle     *string  `protobuf:"bytes,3,opt,name=site_problem_title,json=siteProblemTitle" json:"site_problem_title,omitempty"`
	ContestName          *string  `protobuf:"bytes,4,opt,name=contest_name,json=contestName" json:"contest_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProblemSource) Reset()         { *m = ProblemSource{} }
func (m *ProblemSource) String() string { return proto.CompactTextString(m) }
func (*ProblemSource) ProtoMessage()    {}
func (*ProblemSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0f42fe9a6db7df, []int{3}
}

func (m *ProblemSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemSource.Unmarshal(m, b)
}
func (m *ProblemSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemSource.Marshal(b, m, deterministic)
}
func (m *ProblemSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemSource.Merge(m, src)
}
func (m *ProblemSource) XXX_Size() int {
	return xxx_messageInfo_ProblemSource.Size(m)
}
func (m *ProblemSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemSource.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemSource proto.InternalMessageInfo

func (m *ProblemSource) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *ProblemSource) GetSiteName() string {
	if m != nil && m.SiteName != nil {
		return *m.SiteName
	}
	return ""
}

func (m *ProblemSource) GetSiteProblemTitle() string {
	if m != nil && m.SiteProblemTitle != nil {
		return *m.SiteProblemTitle
	}
	return ""
}

func (m *ProblemSource) GetContestName() string {
	if m != nil && m.ContestName != nil {
		return *m.ContestName
	}
	return ""
}

type ProblemStatement struct {
	// Types that are valid to be assigned to Statement:
	//	*ProblemStatement_Markdown
	Statement            isProblemStatement_Statement `protobuf_oneof:"statement"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ProblemStatement) Reset()         { *m = ProblemStatement{} }
func (m *ProblemStatement) String() string { return proto.CompactTextString(m) }
func (*ProblemStatement) ProtoMessage()    {}
func (*ProblemStatement) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0f42fe9a6db7df, []int{4}
}

func (m *ProblemStatement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemStatement.Unmarshal(m, b)
}
func (m *ProblemStatement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemStatement.Marshal(b, m, deterministic)
}
func (m *ProblemStatement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemStatement.Merge(m, src)
}
func (m *ProblemStatement) XXX_Size() int {
	return xxx_messageInfo_ProblemStatement.Size(m)
}
func (m *ProblemStatement) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemStatement.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemStatement proto.InternalMessageInfo

type isProblemStatement_Statement interface {
	isProblemStatement_Statement()
}

type ProblemStatement_Markdown struct {
	Markdown *MarkdownLatexDocument `protobuf:"bytes,16,opt,name=markdown,oneof"`
}

func (*ProblemStatement_Markdown) isProblemStatement_Statement() {}

func (m *ProblemStatement) GetStatement() isProblemStatement_Statement {
	if m != nil {
		return m.Statement
	}
	return nil
}

func (m *ProblemStatement) GetMarkdown() *MarkdownLatexDocument {
	if x, ok := m.GetStatement().(*ProblemStatement_Markdown); ok {
		return x.Markdown
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProblemStatement) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProblemStatement_Markdown)(nil),
	}
}

type MarkdownLatexDocument struct {
	Text                 *string  `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkdownLatexDocument) Reset()         { *m = MarkdownLatexDocument{} }
func (m *MarkdownLatexDocument) String() string { return proto.CompactTextString(m) }
func (*MarkdownLatexDocument) ProtoMessage()    {}
func (*MarkdownLatexDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0f42fe9a6db7df, []int{5}
}

func (m *MarkdownLatexDocument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkdownLatexDocument.Unmarshal(m, b)
}
func (m *MarkdownLatexDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkdownLatexDocument.Marshal(b, m, deterministic)
}
func (m *MarkdownLatexDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkdownLatexDocument.Merge(m, src)
}
func (m *MarkdownLatexDocument) XXX_Size() int {
	return xxx_messageInfo_MarkdownLatexDocument.Size(m)
}
func (m *MarkdownLatexDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkdownLatexDocument.DiscardUnknown(m)
}

var xxx_messageInfo_MarkdownLatexDocument proto.InternalMessageInfo

func (m *MarkdownLatexDocument) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*Any)(nil), "syzoj.model.Any")
	proto.RegisterType((*UserAuth)(nil), "syzoj.model.UserAuth")
	proto.RegisterType((*DeviceInfo)(nil), "syzoj.model.DeviceInfo")
	proto.RegisterType((*ProblemSource)(nil), "syzoj.model.ProblemSource")
	proto.RegisterType((*ProblemStatement)(nil), "syzoj.model.ProblemStatement")
	proto.RegisterType((*MarkdownLatexDocument)(nil), "syzoj.model.MarkdownLatexDocument")
}

func init() { proto.RegisterFile("syzoj.model.proto", fileDescriptor_ee0f42fe9a6db7df) }

var fileDescriptor_ee0f42fe9a6db7df = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xdd, 0x6e, 0x95, 0x40,
	0x10, 0xc7, 0x3d, 0x1f, 0x26, 0xe7, 0x0c, 0xa7, 0xe6, 0x74, 0x53, 0x13, 0xd4, 0x98, 0xe8, 0xea,
	0x45, 0x13, 0x2d, 0x24, 0x7d, 0x02, 0x69, 0x7a, 0x51, 0x13, 0x35, 0x8a, 0x7a, 0xe3, 0x0d, 0xd9,
	0x03, 0x53, 0xc0, 0xc2, 0x0e, 0xd9, 0x1d, 0x6c, 0xf1, 0x25, 0x7c, 0x65, 0xb3, 0x0b, 0x98, 0x5e,
	0x78, 0x43, 0x86, 0xdf, 0xff, 0x83, 0x99, 0x00, 0xc7, 0x76, 0xf8, 0x4d, 0x3f, 0xa3, 0x96, 0x0a,
	0x6c, 0xa2, 0xce, 0x10, 0x93, 0x08, 0xee, 0xa1, 0xa7, 0x4f, 0x4a, 0xa2, 0xb2, 0xc1, 0xd8, 0x4b,
	0x87, 0xfe, 0x3a, 0x56, 0x7a, 0x18, 0x7d, 0x32, 0x86, 0x55, 0xa2, 0x07, 0x71, 0x0a, 0xeb, 0x42,
	0xb1, 0x0a, 0x17, 0x2f, 0x16, 0xa7, 0xc1, 0xf9, 0x49, 0x34, 0x06, 0xa2, 0x39, 0x10, 0x25, 0x7a,
	0x48, 0xbd, 0x43, 0xc6, 0xb0, 0xf9, 0x6e, 0xd1, 0x24, 0x3d, 0x57, 0xe2, 0x15, 0x1c, 0x75, 0xca,
	0xda, 0x5b, 0x32, 0x45, 0x56, 0x29, 0x5b, 0xf9, 0xf8, 0x2e, 0xdd, 0xcd, 0xf0, 0x4a, 0xd9, 0x4a,
	0x7e, 0x01, 0xb8, 0xc4, 0x5f, 0x75, 0x8e, 0xef, 0xf5, 0x35, 0x89, 0x13, 0x78, 0xc8, 0x74, 0x83,
	0xda, 0x5b, 0xb7, 0xe9, 0xf8, 0x22, 0x9e, 0x03, 0xf4, 0x16, 0x4d, 0xa6, 0x4a, 0xd4, 0x1c, 0xee,
	0xbd, 0xb4, 0x75, 0x24, 0x71, 0x40, 0x3c, 0x82, 0x65, 0xdd, 0x85, 0xc7, 0x1e, 0x2f, 0xeb, 0x4e,
	0xfe, 0x59, 0xc0, 0xd1, 0x67, 0x43, 0x87, 0x06, 0xdb, 0xaf, 0xd4, 0x9b, 0x1c, 0xc5, 0x1e, 0x56,
	0xbd, 0x69, 0xa6, 0x52, 0x37, 0x8a, 0x67, 0xb0, 0xb5, 0x35, 0x63, 0xa6, 0x55, 0x8b, 0xe1, 0xd2,
	0xf3, 0x8d, 0x03, 0x9f, 0x54, 0x8b, 0xe2, 0x2d, 0x08, 0x2f, 0x76, 0x63, 0x49, 0xc6, 0x35, 0x37,
	0x18, 0xae, 0xbc, 0x6b, 0xef, 0x94, 0xa9, 0xfd, 0x9b, 0xe3, 0xe2, 0x25, 0xec, 0x72, 0xd2, 0x8c,
	0x96, 0xc7, 0xb6, 0xb5, 0xf7, 0x05, 0x13, 0x73, 0x85, 0x52, 0xc1, 0x7e, 0x5e, 0x88, 0x15, 0x63,
	0xeb, 0xb6, 0x7e, 0x07, 0x9b, 0x56, 0x99, 0x9b, 0x82, 0x6e, 0xb5, 0x3f, 0x29, 0x38, 0x97, 0xd1,
	0xfd, 0x1f, 0xf5, 0x71, 0x12, 0x3f, 0x28, 0xc6, 0xbb, 0x4b, 0xca, 0x7b, 0x97, 0xba, 0x7a, 0x90,
	0xfe, 0x4b, 0x5d, 0x04, 0xb0, 0xb5, 0x73, 0x9d, 0x7c, 0x03, 0x8f, 0xff, 0x9b, 0x10, 0x02, 0xd6,
	0x8c, 0x77, 0x3c, 0x1d, 0xef, 0xe7, 0x8b, 0xd7, 0x3f, 0x64, 0x59, 0x73, 0xd5, 0x1f, 0xa2, 0x9c,
	0xda, 0xd8, 0x7f, 0x75, 0x7c, 0x9e, 0xe9, 0xf2, 0xac, 0xa4, 0xd8, 0x6f, 0xf0, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x65, 0xf5, 0x63, 0xf1, 0x38, 0x02, 0x00, 0x00,
}
