// Code generated by protoc-gen-go. DO NOT EDIT.
// source: syzoj.db.proto

package database

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/syzoj/syzoj-ng-go/database/protoc-gen-dbmodel/dbmodel"
	model "github.com/syzoj/syzoj-ng-go/model"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   *UserRef             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserName             *string              `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	Auth                 *model.UserAuth      `protobuf:"bytes,3,opt,name=auth" json:"auth,omitempty"`
	RegisterTime         *timestamp.Timestamp `protobuf:"bytes,4,opt,name=register_time,json=registerTime" json:"register_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_549dafe8664ea10e, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() UserRef {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *User) GetAuth() *model.UserAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *User) GetRegisterTime() *timestamp.Timestamp {
	if m != nil {
		return m.RegisterTime
	}
	return nil
}

type Device struct {
	Id                   *DeviceRef        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	User                 *UserRef          `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Info                 *model.DeviceInfo `protobuf:"bytes,3,opt,name=info" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_549dafe8664ea10e, []int{1}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetId() DeviceRef {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Device) GetUser() UserRef {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *Device) GetInfo() *model.DeviceInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type Problem struct {
	Id                   *ProblemRef          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Problemset           *ProblemsetRef       `protobuf:"bytes,2,opt,name=problemset" json:"problemset,omitempty"`
	User                 *UserRef             `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	Problem              *model.Problem       `protobuf:"bytes,5,opt,name=problem" json:"problem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Problem) Reset()         { *m = Problem{} }
func (m *Problem) String() string { return proto.CompactTextString(m) }
func (*Problem) ProtoMessage()    {}
func (*Problem) Descriptor() ([]byte, []int) {
	return fileDescriptor_549dafe8664ea10e, []int{2}
}

func (m *Problem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Problem.Unmarshal(m, b)
}
func (m *Problem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Problem.Marshal(b, m, deterministic)
}
func (m *Problem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Problem.Merge(m, src)
}
func (m *Problem) XXX_Size() int {
	return xxx_messageInfo_Problem.Size(m)
}
func (m *Problem) XXX_DiscardUnknown() {
	xxx_messageInfo_Problem.DiscardUnknown(m)
}

var xxx_messageInfo_Problem proto.InternalMessageInfo

func (m *Problem) GetId() ProblemRef {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Problem) GetProblemset() ProblemsetRef {
	if m != nil && m.Problemset != nil {
		return *m.Problemset
	}
	return ""
}

func (m *Problem) GetUser() UserRef {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *Problem) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Problem) GetProblem() *model.Problem {
	if m != nil {
		return m.Problem
	}
	return nil
}

type Problemset struct {
	Id                   *ProblemsetRef    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	User                 *UserRef          `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Problemset           *model.Problemset `protobuf:"bytes,4,opt,name=problemset" json:"problemset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Problemset) Reset()         { *m = Problemset{} }
func (m *Problemset) String() string { return proto.CompactTextString(m) }
func (*Problemset) ProtoMessage()    {}
func (*Problemset) Descriptor() ([]byte, []int) {
	return fileDescriptor_549dafe8664ea10e, []int{3}
}

func (m *Problemset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Problemset.Unmarshal(m, b)
}
func (m *Problemset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Problemset.Marshal(b, m, deterministic)
}
func (m *Problemset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Problemset.Merge(m, src)
}
func (m *Problemset) XXX_Size() int {
	return xxx_messageInfo_Problemset.Size(m)
}
func (m *Problemset) XXX_DiscardUnknown() {
	xxx_messageInfo_Problemset.DiscardUnknown(m)
}

var xxx_messageInfo_Problemset proto.InternalMessageInfo

func (m *Problemset) GetId() ProblemsetRef {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Problemset) GetUser() UserRef {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *Problemset) GetProblemset() *model.Problemset {
	if m != nil {
		return m.Problemset
	}
	return nil
}

type Submission struct {
	Id                   *SubmissionRef    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	User                 *UserRef          `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Problemset           *ProblemsetRef    `protobuf:"bytes,4,opt,name=problemset" json:"problemset,omitempty"`
	Problem              *ProblemRef       `protobuf:"bytes,5,opt,name=problem" json:"problem,omitempty"`
	Submission           *model.Submission `protobuf:"bytes,17,opt,name=submission" json:"submission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Submission) Reset()         { *m = Submission{} }
func (m *Submission) String() string { return proto.CompactTextString(m) }
func (*Submission) ProtoMessage()    {}
func (*Submission) Descriptor() ([]byte, []int) {
	return fileDescriptor_549dafe8664ea10e, []int{4}
}

func (m *Submission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Submission.Unmarshal(m, b)
}
func (m *Submission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Submission.Marshal(b, m, deterministic)
}
func (m *Submission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Submission.Merge(m, src)
}
func (m *Submission) XXX_Size() int {
	return xxx_messageInfo_Submission.Size(m)
}
func (m *Submission) XXX_DiscardUnknown() {
	xxx_messageInfo_Submission.DiscardUnknown(m)
}

var xxx_messageInfo_Submission proto.InternalMessageInfo

func (m *Submission) GetId() SubmissionRef {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Submission) GetUser() UserRef {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *Submission) GetProblemset() ProblemsetRef {
	if m != nil && m.Problemset != nil {
		return *m.Problemset
	}
	return ""
}

func (m *Submission) GetProblem() ProblemRef {
	if m != nil && m.Problem != nil {
		return *m.Problem
	}
	return ""
}

func (m *Submission) GetSubmission() *model.Submission {
	if m != nil {
		return m.Submission
	}
	return nil
}

type Judger struct {
	Id                   *JudgerRef `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Token                *string    `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Judger) Reset()         { *m = Judger{} }
func (m *Judger) String() string { return proto.CompactTextString(m) }
func (*Judger) ProtoMessage()    {}
func (*Judger) Descriptor() ([]byte, []int) {
	return fileDescriptor_549dafe8664ea10e, []int{5}
}

func (m *Judger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Judger.Unmarshal(m, b)
}
func (m *Judger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Judger.Marshal(b, m, deterministic)
}
func (m *Judger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Judger.Merge(m, src)
}
func (m *Judger) XXX_Size() int {
	return xxx_messageInfo_Judger.Size(m)
}
func (m *Judger) XXX_DiscardUnknown() {
	xxx_messageInfo_Judger.DiscardUnknown(m)
}

var xxx_messageInfo_Judger proto.InternalMessageInfo

func (m *Judger) GetId() JudgerRef {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Judger) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "syzoj.db.User")
	proto.RegisterType((*Device)(nil), "syzoj.db.Device")
	proto.RegisterType((*Problem)(nil), "syzoj.db.Problem")
	proto.RegisterType((*Problemset)(nil), "syzoj.db.Problemset")
	proto.RegisterType((*Submission)(nil), "syzoj.db.Submission")
	proto.RegisterType((*Judger)(nil), "syzoj.db.Judger")
}

func init() { proto.RegisterFile("syzoj.db.proto", fileDescriptor_549dafe8664ea10e) }

var fileDescriptor_549dafe8664ea10e = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xb5, 0xa9, 0x9b, 0x34, 0x93, 0x36, 0x52, 0x56, 0x45, 0x98, 0x5c, 0x1a, 0x59, 0x20,
	0x82, 0x50, 0x37, 0x2a, 0x17, 0xce, 0x44, 0x3d, 0x00, 0x07, 0x14, 0x2d, 0x70, 0xe1, 0x52, 0xad,
	0xe3, 0x89, 0xb3, 0x10, 0x7b, 0x23, 0xef, 0xba, 0x52, 0x79, 0x04, 0x0e, 0xbc, 0x0b, 0x8f, 0xc1,
	0x99, 0x47, 0xe0, 0x45, 0xd0, 0x7a, 0xed, 0xd4, 0x21, 0x8e, 0xaa, 0x5c, 0x56, 0xd9, 0xf9, 0x67,
	0xf6, 0xff, 0xe6, 0x4f, 0x02, 0x7d, 0x7d, 0xf7, 0x5d, 0x7d, 0x65, 0x51, 0xc8, 0xd6, 0x99, 0x32,
	0x8a, 0x9e, 0x54, 0xf7, 0xe1, 0x59, 0x14, 0x26, 0x2a, 0xc2, 0x95, 0x13, 0x86, 0x03, 0x27, 0xd4,
	0x4b, 0x17, 0xb1, 0x52, 0xf1, 0x0a, 0x27, 0xc5, 0x2d, 0xcc, 0x17, 0x13, 0x23, 0x13, 0xd4, 0x46,
	0x24, 0xeb, 0xb2, 0xe1, 0xc9, 0xff, 0x0d, 0x22, 0xbd, 0x73, 0x52, 0xf0, 0x8b, 0x80, 0xf7, 0x59,
	0x63, 0x46, 0xfb, 0xd0, 0x92, 0x91, 0x4f, 0x46, 0x64, 0xdc, 0xe5, 0x2d, 0x19, 0xd1, 0xa7, 0xd0,
	0xcd, 0x35, 0x66, 0x37, 0xa9, 0x48, 0xd0, 0x6f, 0xd9, 0xf2, 0xb4, 0xf3, 0xe3, 0xf7, 0x4f, 0xd2,
	0x1a, 0x11, 0x7e, 0x62, 0x95, 0x0f, 0x22, 0x41, 0xfa, 0x02, 0x3c, 0x91, 0x9b, 0xa5, 0x7f, 0x34,
	0x22, 0xe3, 0xde, 0xab, 0x47, 0xac, 0x0e, 0x67, 0x9f, 0x7d, 0x93, 0x9b, 0x25, 0x2f, 0x5a, 0xe8,
	0x5b, 0x38, 0xcb, 0x30, 0x96, 0xda, 0x60, 0x76, 0x63, 0x01, 0x7d, 0xaf, 0x98, 0x19, 0x32, 0x07,
	0xc7, 0x2a, 0x38, 0xf6, 0xa9, 0xa2, 0x2f, 0x0d, 0x7d, 0xc2, 0x4f, 0xab, 0x49, 0xab, 0x05, 0x0b,
	0x68, 0x5f, 0xe3, 0xad, 0x9c, 0xe3, 0x0e, 0xf4, 0x05, 0x78, 0x16, 0xad, 0xe4, 0xed, 0xd9, 0xf1,
	0x36, 0x2d, 0x4a, 0xbc, 0x38, 0xe9, 0x4b, 0xf0, 0x64, 0xba, 0x50, 0x25, 0xef, 0xe3, 0x2d, 0x5e,
	0xf7, 0xe6, 0xbb, 0x74, 0xa1, 0x78, 0xd1, 0x14, 0xfc, 0x25, 0xd0, 0x99, 0x65, 0x2a, 0x5c, 0x61,
	0xb2, 0xe3, 0x74, 0x05, 0xb0, 0x76, 0x92, 0x46, 0x53, 0xfa, 0x0d, 0xac, 0xdf, 0x29, 0xad, 0x09,
	0xbc, 0xf6, 0x79, 0x03, 0x77, 0xb4, 0x0f, 0xee, 0x1a, 0x7a, 0xf3, 0x0c, 0x85, 0xc1, 0x83, 0xf3,
	0x01, 0x37, 0x67, 0x15, 0xca, 0xa0, 0x53, 0x9a, 0xfa, 0xc7, 0xc5, 0x0b, 0xe7, 0x5b, 0x5b, 0x96,
	0x0b, 0xf1, 0xaa, 0x29, 0xb8, 0x05, 0x98, 0xdd, 0x43, 0xee, 0x4b, 0x74, 0x2f, 0xf4, 0xeb, 0xad,
	0x20, 0xbc, 0x86, 0x5c, 0x67, 0x8d, 0x71, 0x04, 0x7f, 0x08, 0xc0, 0xc7, 0x3c, 0x4c, 0xa4, 0xd6,
	0x52, 0xa5, 0x87, 0x1b, 0x5f, 0xed, 0x18, 0x3f, 0xf8, 0x0d, 0x8c, 0xb7, 0xa3, 0xe9, 0x4e, 0xfb,
	0xb6, 0xbf, 0x4b, 0xab, 0xea, 0x26, 0x14, 0xbb, 0x95, 0xde, 0xb0, 0xf9, 0x83, 0x86, 0xad, 0xee,
	0xd1, 0x79, 0xad, 0x35, 0x60, 0xd0, 0x7e, 0x9f, 0x47, 0x71, 0xc3, 0x1f, 0xea, 0x1c, 0x8e, 0x8d,
	0xfa, 0x86, 0xa9, 0xfb, 0xb1, 0x70, 0x77, 0x99, 0x3e, 0xff, 0xf2, 0x2c, 0x96, 0x66, 0x99, 0x87,
	0x6c, 0xae, 0x92, 0x49, 0x61, 0xe0, 0xce, 0xcb, 0x34, 0xbe, 0x8c, 0xd5, 0x24, 0x12, 0x46, 0x84,
	0x42, 0xe3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xec, 0x65, 0x00, 0x21, 0x04, 0x00, 0x00,
}
