// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: syzoj.service.problem.rpc.proto

package rpc // import "github.com/syzoj/syzoj-ng-go/service/problem/rpc"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/syzoj/syzoj-ng-go/model/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Error int32

const (
	Error_Unknown         Error = 0
	Error_BadRequest      Error = 1
	Error_ProblemNotFound Error = 2
)

var Error_name = map[int32]string{
	0: "Unknown",
	1: "BadRequest",
	2: "ProblemNotFound",
}
var Error_value = map[string]int32{
	"Unknown":         0,
	"BadRequest":      1,
	"ProblemNotFound": 2,
}

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}
func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}
func (x *Error) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Error_value, data, "Error")
	if err != nil {
		return err
	}
	*x = Error(value)
	return nil
}
func (Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_service_problem_rpc_85329bb42a03e39e, []int{0}
}

type CreateProblemRequest struct {
	Title                *string  `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProblemRequest) Reset()         { *m = CreateProblemRequest{} }
func (m *CreateProblemRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProblemRequest) ProtoMessage()    {}
func (*CreateProblemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_service_problem_rpc_85329bb42a03e39e, []int{0}
}
func (m *CreateProblemRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateProblemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateProblemRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *CreateProblemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProblemRequest.Merge(dst, src)
}
func (m *CreateProblemRequest) XXX_Size() int {
	return m.Size()
}
func (m *CreateProblemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProblemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProblemRequest proto.InternalMessageInfo

func (m *CreateProblemRequest) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

type CreateProblemResponse struct {
	Error                *Error          `protobuf:"varint,1,opt,name=error,enum=syzoj.service.problem.rpc.Error" json:"error,omitempty"`
	Problem              *common.Problem `protobuf:"bytes,2,opt,name=problem" json:"problem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateProblemResponse) Reset()         { *m = CreateProblemResponse{} }
func (m *CreateProblemResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProblemResponse) ProtoMessage()    {}
func (*CreateProblemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_service_problem_rpc_85329bb42a03e39e, []int{1}
}
func (m *CreateProblemResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateProblemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateProblemResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *CreateProblemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProblemResponse.Merge(dst, src)
}
func (m *CreateProblemResponse) XXX_Size() int {
	return m.Size()
}
func (m *CreateProblemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProblemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProblemResponse proto.InternalMessageInfo

func (m *CreateProblemResponse) GetError() Error {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Error_Unknown
}

func (m *CreateProblemResponse) GetProblem() *common.Problem {
	if m != nil {
		return m.Problem
	}
	return nil
}

type UpdateProblemStatementRequest struct {
	ProblemId            *string                  `protobuf:"bytes,1,opt,name=problem_id,json=problemId" json:"problem_id,omitempty"`
	Statement            *common.ProblemStatement `protobuf:"bytes,2,opt,name=statement" json:"statement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *UpdateProblemStatementRequest) Reset()         { *m = UpdateProblemStatementRequest{} }
func (m *UpdateProblemStatementRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProblemStatementRequest) ProtoMessage()    {}
func (*UpdateProblemStatementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_service_problem_rpc_85329bb42a03e39e, []int{2}
}
func (m *UpdateProblemStatementRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateProblemStatementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateProblemStatementRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *UpdateProblemStatementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProblemStatementRequest.Merge(dst, src)
}
func (m *UpdateProblemStatementRequest) XXX_Size() int {
	return m.Size()
}
func (m *UpdateProblemStatementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProblemStatementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProblemStatementRequest proto.InternalMessageInfo

func (m *UpdateProblemStatementRequest) GetProblemId() string {
	if m != nil && m.ProblemId != nil {
		return *m.ProblemId
	}
	return ""
}

func (m *UpdateProblemStatementRequest) GetStatement() *common.ProblemStatement {
	if m != nil {
		return m.Statement
	}
	return nil
}

type UpdateProblemStatementResponse struct {
	Error                *Error   `protobuf:"varint,1,opt,name=error,enum=syzoj.service.problem.rpc.Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProblemStatementResponse) Reset()         { *m = UpdateProblemStatementResponse{} }
func (m *UpdateProblemStatementResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProblemStatementResponse) ProtoMessage()    {}
func (*UpdateProblemStatementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_service_problem_rpc_85329bb42a03e39e, []int{3}
}
func (m *UpdateProblemStatementResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateProblemStatementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateProblemStatementResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *UpdateProblemStatementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProblemStatementResponse.Merge(dst, src)
}
func (m *UpdateProblemStatementResponse) XXX_Size() int {
	return m.Size()
}
func (m *UpdateProblemStatementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProblemStatementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProblemStatementResponse proto.InternalMessageInfo

func (m *UpdateProblemStatementResponse) GetError() Error {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Error_Unknown
}

type ListProblemRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProblemRequest) Reset()         { *m = ListProblemRequest{} }
func (m *ListProblemRequest) String() string { return proto.CompactTextString(m) }
func (*ListProblemRequest) ProtoMessage()    {}
func (*ListProblemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_service_problem_rpc_85329bb42a03e39e, []int{4}
}
func (m *ListProblemRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListProblemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListProblemRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ListProblemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProblemRequest.Merge(dst, src)
}
func (m *ListProblemRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListProblemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProblemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProblemRequest proto.InternalMessageInfo

type ListProblemResponse struct {
	Error                *Error            `protobuf:"varint,1,opt,name=error,enum=syzoj.service.problem.rpc.Error" json:"error,omitempty"`
	Problem              []*common.Problem `protobuf:"bytes,2,rep,name=problem" json:"problem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListProblemResponse) Reset()         { *m = ListProblemResponse{} }
func (m *ListProblemResponse) String() string { return proto.CompactTextString(m) }
func (*ListProblemResponse) ProtoMessage()    {}
func (*ListProblemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_syzoj_service_problem_rpc_85329bb42a03e39e, []int{5}
}
func (m *ListProblemResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListProblemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListProblemResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ListProblemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProblemResponse.Merge(dst, src)
}
func (m *ListProblemResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListProblemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProblemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProblemResponse proto.InternalMessageInfo

func (m *ListProblemResponse) GetError() Error {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Error_Unknown
}

func (m *ListProblemResponse) GetProblem() []*common.Problem {
	if m != nil {
		return m.Problem
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateProblemRequest)(nil), "syzoj.service.problem.rpc.CreateProblemRequest")
	proto.RegisterType((*CreateProblemResponse)(nil), "syzoj.service.problem.rpc.CreateProblemResponse")
	proto.RegisterType((*UpdateProblemStatementRequest)(nil), "syzoj.service.problem.rpc.UpdateProblemStatementRequest")
	proto.RegisterType((*UpdateProblemStatementResponse)(nil), "syzoj.service.problem.rpc.UpdateProblemStatementResponse")
	proto.RegisterType((*ListProblemRequest)(nil), "syzoj.service.problem.rpc.ListProblemRequest")
	proto.RegisterType((*ListProblemResponse)(nil), "syzoj.service.problem.rpc.ListProblemResponse")
	proto.RegisterEnum("syzoj.service.problem.rpc.Error", Error_name, Error_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProblemClient is the client API for Problem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProblemClient interface {
	CreateProblem(ctx context.Context, in *CreateProblemRequest, opts ...grpc.CallOption) (*CreateProblemResponse, error)
	UpdateProblemStatement(ctx context.Context, in *UpdateProblemStatementRequest, opts ...grpc.CallOption) (*UpdateProblemStatementResponse, error)
	ListProblem(ctx context.Context, in *ListProblemRequest, opts ...grpc.CallOption) (*ListProblemResponse, error)
}

type problemClient struct {
	cc *grpc.ClientConn
}

func NewProblemClient(cc *grpc.ClientConn) ProblemClient {
	return &problemClient{cc}
}

func (c *problemClient) CreateProblem(ctx context.Context, in *CreateProblemRequest, opts ...grpc.CallOption) (*CreateProblemResponse, error) {
	out := new(CreateProblemResponse)
	err := c.cc.Invoke(ctx, "/syzoj.service.problem.rpc.Problem/CreateProblem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) UpdateProblemStatement(ctx context.Context, in *UpdateProblemStatementRequest, opts ...grpc.CallOption) (*UpdateProblemStatementResponse, error) {
	out := new(UpdateProblemStatementResponse)
	err := c.cc.Invoke(ctx, "/syzoj.service.problem.rpc.Problem/UpdateProblemStatement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemClient) ListProblem(ctx context.Context, in *ListProblemRequest, opts ...grpc.CallOption) (*ListProblemResponse, error) {
	out := new(ListProblemResponse)
	err := c.cc.Invoke(ctx, "/syzoj.service.problem.rpc.Problem/ListProblem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProblemServer is the server API for Problem service.
type ProblemServer interface {
	CreateProblem(context.Context, *CreateProblemRequest) (*CreateProblemResponse, error)
	UpdateProblemStatement(context.Context, *UpdateProblemStatementRequest) (*UpdateProblemStatementResponse, error)
	ListProblem(context.Context, *ListProblemRequest) (*ListProblemResponse, error)
}

func RegisterProblemServer(s *grpc.Server, srv ProblemServer) {
	s.RegisterService(&_Problem_serviceDesc, srv)
}

func _Problem_CreateProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).CreateProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syzoj.service.problem.rpc.Problem/CreateProblem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).CreateProblem(ctx, req.(*CreateProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_UpdateProblemStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProblemStatementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).UpdateProblemStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syzoj.service.problem.rpc.Problem/UpdateProblemStatement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).UpdateProblemStatement(ctx, req.(*UpdateProblemStatementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Problem_ListProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemServer).ListProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syzoj.service.problem.rpc.Problem/ListProblem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemServer).ListProblem(ctx, req.(*ListProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Problem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "syzoj.service.problem.rpc.Problem",
	HandlerType: (*ProblemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProblem",
			Handler:    _Problem_CreateProblem_Handler,
		},
		{
			MethodName: "UpdateProblemStatement",
			Handler:    _Problem_UpdateProblemStatement_Handler,
		},
		{
			MethodName: "ListProblem",
			Handler:    _Problem_ListProblem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "syzoj.service.problem.rpc.proto",
}

func (m *CreateProblemRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateProblemRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Title != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSyzojServiceProblemRpc(dAtA, i, uint64(len(*m.Title)))
		i += copy(dAtA[i:], *m.Title)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *CreateProblemResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateProblemResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Error != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSyzojServiceProblemRpc(dAtA, i, uint64(*m.Error))
	}
	if m.Problem != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSyzojServiceProblemRpc(dAtA, i, uint64(m.Problem.Size()))
		n1, err := m.Problem.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *UpdateProblemStatementRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateProblemStatementRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ProblemId != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintSyzojServiceProblemRpc(dAtA, i, uint64(len(*m.ProblemId)))
		i += copy(dAtA[i:], *m.ProblemId)
	}
	if m.Statement != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintSyzojServiceProblemRpc(dAtA, i, uint64(m.Statement.Size()))
		n2, err := m.Statement.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *UpdateProblemStatementResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateProblemStatementResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Error != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSyzojServiceProblemRpc(dAtA, i, uint64(*m.Error))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ListProblemRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListProblemRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ListProblemResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListProblemResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Error != nil {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSyzojServiceProblemRpc(dAtA, i, uint64(*m.Error))
	}
	if len(m.Problem) > 0 {
		for _, msg := range m.Problem {
			dAtA[i] = 0x12
			i++
			i = encodeVarintSyzojServiceProblemRpc(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintSyzojServiceProblemRpc(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CreateProblemRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Title != nil {
		l = len(*m.Title)
		n += 1 + l + sovSyzojServiceProblemRpc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CreateProblemResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Error != nil {
		n += 1 + sovSyzojServiceProblemRpc(uint64(*m.Error))
	}
	if m.Problem != nil {
		l = m.Problem.Size()
		n += 1 + l + sovSyzojServiceProblemRpc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UpdateProblemStatementRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProblemId != nil {
		l = len(*m.ProblemId)
		n += 1 + l + sovSyzojServiceProblemRpc(uint64(l))
	}
	if m.Statement != nil {
		l = m.Statement.Size()
		n += 1 + l + sovSyzojServiceProblemRpc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *UpdateProblemStatementResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Error != nil {
		n += 1 + sovSyzojServiceProblemRpc(uint64(*m.Error))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListProblemRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListProblemResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Error != nil {
		n += 1 + sovSyzojServiceProblemRpc(uint64(*m.Error))
	}
	if len(m.Problem) > 0 {
		for _, e := range m.Problem {
			l = e.Size()
			n += 1 + l + sovSyzojServiceProblemRpc(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSyzojServiceProblemRpc(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozSyzojServiceProblemRpc(x uint64) (n int) {
	return sovSyzojServiceProblemRpc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CreateProblemRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojServiceProblemRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateProblemRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateProblemRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojServiceProblemRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyzojServiceProblemRpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.Title = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojServiceProblemRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojServiceProblemRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateProblemResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojServiceProblemRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateProblemResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateProblemResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var v Error
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojServiceProblemRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (Error(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Error = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Problem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojServiceProblemRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyzojServiceProblemRpc
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Problem == nil {
				m.Problem = &common.Problem{}
			}
			if err := m.Problem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojServiceProblemRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojServiceProblemRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateProblemStatementRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojServiceProblemRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateProblemStatementRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateProblemStatementRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProblemId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojServiceProblemRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSyzojServiceProblemRpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.ProblemId = &s
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Statement", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojServiceProblemRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyzojServiceProblemRpc
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Statement == nil {
				m.Statement = &common.ProblemStatement{}
			}
			if err := m.Statement.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojServiceProblemRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojServiceProblemRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateProblemStatementResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojServiceProblemRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateProblemStatementResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateProblemStatementResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var v Error
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojServiceProblemRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (Error(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Error = &v
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojServiceProblemRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojServiceProblemRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListProblemRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojServiceProblemRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListProblemRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListProblemRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojServiceProblemRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojServiceProblemRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListProblemResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSyzojServiceProblemRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListProblemResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListProblemResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var v Error
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojServiceProblemRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (Error(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Error = &v
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Problem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSyzojServiceProblemRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSyzojServiceProblemRpc
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Problem = append(m.Problem, &common.Problem{})
			if err := m.Problem[len(m.Problem)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSyzojServiceProblemRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSyzojServiceProblemRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSyzojServiceProblemRpc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSyzojServiceProblemRpc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSyzojServiceProblemRpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSyzojServiceProblemRpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthSyzojServiceProblemRpc
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSyzojServiceProblemRpc
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSyzojServiceProblemRpc(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSyzojServiceProblemRpc = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSyzojServiceProblemRpc   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("syzoj.service.problem.rpc.proto", fileDescriptor_syzoj_service_problem_rpc_85329bb42a03e39e)
}

var fileDescriptor_syzoj_service_problem_rpc_85329bb42a03e39e = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5f, 0x6b, 0xda, 0x50,
	0x14, 0xdf, 0x75, 0x88, 0xe4, 0xc8, 0x9c, 0x5c, 0x75, 0xb8, 0x80, 0x51, 0xf2, 0x24, 0x63, 0x26,
	0xe2, 0xc3, 0x98, 0x30, 0xf6, 0xe0, 0xd8, 0x60, 0x30, 0x46, 0x49, 0x11, 0x4a, 0x5f, 0x8a, 0x26,
	0x17, 0x9b, 0x36, 0xb9, 0x37, 0xbd, 0xb9, 0xb6, 0xb4, 0x94, 0xd2, 0x2f, 0xd0, 0xef, 0xd5, 0xc7,
	0x7e, 0x84, 0xe2, 0xd7, 0xe8, 0x4b, 0xd1, 0x7b, 0x83, 0x4d, 0xab, 0xa9, 0xb4, 0x7d, 0x09, 0x39,
	0x27, 0xbf, 0x7f, 0x9c, 0x73, 0x08, 0x34, 0xe3, 0xd3, 0x33, 0x76, 0x60, 0xc5, 0x84, 0x1f, 0xfb,
	0x2e, 0xb1, 0x22, 0xce, 0xc6, 0x01, 0x09, 0x2d, 0x1e, 0xb9, 0xf3, 0x77, 0xc1, 0xf0, 0xe7, 0xb5,
	0x00, 0xbd, 0x19, 0x32, 0x8f, 0x04, 0xb6, 0xcb, 0xc2, 0x90, 0x51, 0x5b, 0xe2, 0x64, 0x21, 0xb9,
	0xe6, 0x57, 0xa8, 0xfe, 0xe2, 0x64, 0x24, 0xc8, 0x96, 0x64, 0x39, 0xe4, 0x68, 0x4a, 0x62, 0x81,
	0xab, 0x90, 0x17, 0xbe, 0x08, 0x48, 0x3d, 0xd7, 0x42, 0x6d, 0xcd, 0x91, 0x85, 0x79, 0x89, 0xa0,
	0xf6, 0x08, 0x1e, 0x47, 0x8c, 0xc6, 0x04, 0x7f, 0x83, 0x3c, 0xe1, 0x9c, 0xf1, 0x3a, 0x6a, 0xa1,
	0x76, 0xa9, 0xd7, 0xb2, 0xd6, 0x87, 0xfe, 0x3d, 0xc7, 0x39, 0x12, 0x8e, 0x6d, 0x28, 0xa8, 0x6f,
	0x0b, 0xa7, 0x62, 0xaf, 0x66, 0xa5, 0x52, 0x26, 0x3e, 0x09, 0xca, 0x3c, 0x87, 0xc6, 0x30, 0xf2,
	0x96, 0x09, 0xb6, 0xc5, 0x48, 0x90, 0x90, 0x50, 0x91, 0x24, 0x6f, 0x00, 0x28, 0xec, 0x9e, 0xef,
	0x2d, 0xe2, 0x68, 0x8e, 0xa6, 0x3a, 0x7f, 0x3d, 0xfc, 0x03, 0xb4, 0x38, 0xa1, 0x28, 0x4b, 0x63,
	0xa5, 0xe5, 0x52, 0x78, 0x49, 0x30, 0x77, 0xc0, 0x58, 0xe7, 0xfe, 0xba, 0x41, 0x98, 0x55, 0xc0,
	0xff, 0xfc, 0x58, 0xa4, 0xd7, 0x60, 0x5e, 0x40, 0x25, 0xd5, 0x7d, 0xcb, 0x69, 0xbf, 0x7f, 0x7e,
	0xda, 0x5f, 0xfa, 0x90, 0x5f, 0x08, 0xe0, 0x22, 0x14, 0x86, 0xf4, 0x90, 0xb2, 0x13, 0x5a, 0x7e,
	0x87, 0x4b, 0x00, 0x83, 0x91, 0xa7, 0x32, 0x96, 0x11, 0xae, 0xc0, 0x47, 0xc5, 0xfc, 0xcf, 0xc4,
	0x1f, 0x36, 0xa5, 0x5e, 0x39, 0xd7, 0xbb, 0xcb, 0x41, 0x41, 0x75, 0x31, 0x87, 0x0f, 0xa9, 0xb3,
	0xc1, 0x76, 0x46, 0xe2, 0x55, 0xf7, 0xa8, 0x77, 0x37, 0x27, 0xa8, 0x19, 0x5d, 0x21, 0xf8, 0xb4,
	0x7a, 0x57, 0xf8, 0x7b, 0x86, 0x58, 0xe6, 0x71, 0xe9, 0xfd, 0x17, 0x30, 0x55, 0x9e, 0x00, 0x8a,
	0x0f, 0x56, 0x89, 0x3b, 0x19, 0x4a, 0x4f, 0x0f, 0x41, 0xb7, 0x36, 0x85, 0x4b, 0xb7, 0xc1, 0xcf,
	0xeb, 0x99, 0x81, 0x6e, 0x66, 0x06, 0xba, 0x9d, 0x19, 0x68, 0xb7, 0x3b, 0xf1, 0xc5, 0xfe, 0x74,
	0x3c, 0x5f, 0xb3, 0xfc, 0x09, 0xc8, 0x67, 0x87, 0x4e, 0x3a, 0x13, 0x66, 0x2b, 0x4d, 0x5b, 0x69,
	0xda, 0x3c, 0x72, 0xef, 0x03, 0x00, 0x00, 0xff, 0xff, 0xde, 0xc9, 0xf2, 0xdd, 0x75, 0x04, 0x00,
	0x00,
}
